# Generated by Django 4.2.6 on 2023-10-21 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0005_turfcategory_turf_turfcategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='slot_id',
            new_name='slot',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='turf_id',
            new_name='turf',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='location_id',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='turfcategory_id',
            new_name='turfcategory',
        ),
        migrations.RenameField(
            model_name='turf',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='turf_multi_image',
            old_name='turf_id',
            new_name='turf',
        ),
    ]
