# Generated by Django 4.2.6 on 2023-10-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0006_rename_slot_id_booking_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turfApp.location'),
        ),
    ]
