# Generated by Django 4.2.6 on 2023-10-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0008_alter_turf_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
