# Generated by Django 4.2.6 on 2023-10-24 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0012_remove_turf_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='turf_multi_image',
            name='turf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turfApp.turf'),
        ),
    ]
