# Generated by Django 4.2.6 on 2023-10-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0013_turf_price_alter_turf_multi_image_turf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turf',
            old_name='price',
            new_name='amount',
        ),
    ]
