# Generated by Django 4.2.6 on 2023-10-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0014_rename_price_turf_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_multi_image',
            name='turf',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='turfApp.turf'),
        ),
    ]
