# Generated by Django 4.2.6 on 2023-10-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0016_alter_turf_multi_image_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_multi_image',
            name='img',
            field=models.FileField(upload_to='uploads/images'),
        ),
    ]
