# Generated by Django 4.2.6 on 2023-10-25 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0017_alter_turf_multi_image_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_multi_image',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
