# Generated by Django 4.2.6 on 2023-10-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0020_alter_turf_multi_image_turf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_multi_image',
            name='turf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfApp.turf'),
        ),
    ]
