# Generated by Django 4.2.6 on 2023-10-26 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0021_alter_turf_multi_image_turf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Turf_multi_image',
        ),
    ]
