# Generated by Django 4.2.6 on 2023-10-26 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0022_delete_turf_multi_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turf_multi_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(blank=True, null=True, upload_to='uploads/images')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfApp.turf')),
            ],
        ),
    ]
