# Generated by Django 4.2.6 on 2023-10-26 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0023_turf_multi_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turf_multi_image',
            name='turf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turfApp.turf'),
        ),
    ]
