# Generated by Django 4.2.6 on 2023-11-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0029_booking_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.FileField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
