# Generated by Django 4.2.6 on 2023-11-07 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0030_profile_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('feedback', models.TextField(blank=True, max_length=500)),
                ('place', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
