# Generated by Django 4.2.6 on 2023-11-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0032_remove_feedback_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10),
        ),
    ]
