# Generated by Django 4.2.6 on 2023-11-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0033_profile_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], max_length=10),
        ),
    ]
