# Generated by Django 4.2.6 on 2023-11-10 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('turfApp', '0034_alter_profile_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='advertisement_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
        migrations.AddField(
            model_name='turf',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
