# Generated by Django 4.2.6 on 2023-11-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0035_turf_advertisement_image_turf_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turf',
            name='user',
        ),
    ]
