# Generated by Django 4.2.6 on 2023-11-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0037_turf_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='turf',
            name='advertisement_images',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/images'),
        ),
    ]
