# Generated by Django 4.2.6 on 2023-11-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0040_alter_turf_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
    ]
