# Generated by Django 4.2.6 on 2023-11-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0041_admincontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincontact',
            name='whatsapp_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
