# Generated by Django 4.2.6 on 2023-11-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0042_alter_admincontact_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincontact',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
