# Generated by Django 4.2.6 on 2023-11-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0043_alter_admincontact_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincontact',
            name='whatsapp_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
