# Generated by Django 4.2.6 on 2023-11-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0046_alter_admincontact_whatsapp_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminContact',
        ),
        migrations.AddField(
            model_name='post',
            name='admin_whtsappnumber',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
