# Generated by Django 4.2.6 on 2023-11-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0047_delete_admincontact_post_admin_whtsappnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='admin_whtsappnumber',
            field=models.IntegerField(),
        ),
    ]
