# Generated by Django 4.2.6 on 2023-11-14 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0049_alter_post_admin_whtsappnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='admin_whtsappnumber',
        ),
    ]
