# Generated by Django 4.1.4 on 2023-12-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0051_remove_profile_user_role_profile_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='no_of_booking',
            field=models.IntegerField(default=1),
        ),
    ]
