# Generated by Django 4.2.6 on 2023-12-30 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0053_userblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='turf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='turfApp.turf'),
        ),
    ]
