# Generated by Django 4.2.6 on 2024-01-02 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turfApp', '0056_contact_address_contact_email_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
